Repository MoneyVill/Frontend, pull requests merged in 2024-11, with the labels that each got.

#8 💡 initial commit
  money-vill/.gitignore
  money-vill/README.md
  money-vill/package-lock.json
  money-vill/package.json
  money-vill/public/favicon.ico
  money-vill/public/index.html
  money-vill/public/logo192.png
  money-vill/public/logo512.png
  money-vill/public/manifest.json
  money-vill/public/robots.txt
  money-vill/src/App.css
  money-vill/src/App.test.tsx
  money-vill/src/App.tsx
  money-vill/src/index.css
  money-vill/src/index.tsx
  money-vill/src/logo.svg
  money-vill/src/react-app-env.d.ts
  money-vill/src/reportWebVitals.ts
  money-vill/src/setupTests.ts
  money-vill/tsconfig.json
Labels: ⚙️ 환경 설정

#9 Feat:Update loginAPI
  package.json
  src/api/common/getTokenStatusAPI.ts
  src/api/common/postLoginAPI.ts
  src/api/cookie.ts
  src/api/hello.ts
  src/api/instance.ts
  src/hooks/useGetTokenStatus.tsx
  src/pages/student/login.tsx
  src/pages/teacher/login.tsx
  yarn.lock
Labels: 💡 기능

#10 💡학생 회원가입
  package.json
  src/api/cookie.ts
  src/api/hello.ts
  src/api/instance.ts
  src/hooks/useGetTokenStatus.tsx
  src/pages/student/login.tsx
  src/pages/teacher/login.tsx
  yarn.lock
Labels: 🚨 버그, 💡 기능

#16 💡 Add: Page createnation
  public/assets/create/create_illust_11.png
  public/assets/create/create_illust_22.png
  src/pages/teacher/create.tsx
  yarn.lock
Labels: 💡 기능

#18 📢: 회원가입 시 중복확인 api 변경
  src/api/common/postDuplicationCheckAPI.ts
Labels: 📢 변경

#24 FE-08
  src/api/common/postDuplicationCheckAPI.ts
  src/api/student/user/postStudentAPI.ts
  src/api/teacher/user/postTeacherAPI.ts
  src/hooks/useGetTokenStatus.tsx
  src/hooks/useNavigate.tsx
  src/pages/student/login.tsx
  src/pages/student/signup.tsx
  src/pages/teacher/create.tsx
  src/pages/teacher/login.tsx
  src/pages/teacher/signup.tsx
Labels: 🚨 버그, 📢 변경, 🍎 chore
